from dataclasses import dataclass, asdict


@dataclass(frozen=True)
class Context:
    name: str
    amount: float
    unit: str
    ounces: float


CONTEXTS = [Context("Water (contexts)", 1, "cup", 8),
            Context("All-Purpose Flour", 1.0, "cup", 4.25),
            Context("Almond Flour", 1.0, "cup", 3.375),
            Context("Almond meal", 1.0, "cup", 3.0),
            Context("Almond paste (packed)", 1.0, "cup", 9.125),
            Context("Almonds (sliced)", 0.5, "cup", 1.5),
            Context("Almonds (slivered)", 0.5, "cup", 2.0),
            Context("Almonds, whole (unblanched)", 1.0, "cup", 5.0),
            Context("Amaranth flour", 1.0, "cup", 3.625),
            Context("Apple juice concentrate", 0.25, "cup", 2.5),
            Context("Apples (dried, diced)", 1.0, "cup", 3.0),
            Context("Apples (peeled, sliced)", 1.0, "cup", 4.0),
            Context("Applesauce", 1.0, "cup", 9.0),
            Context("Apricots (dried, diced)", 0.5, "cup", 2.25),
            Context("Artisan Bread Flour", 1.0, "cup", 4.25),
            Context("Artisan Bread Topping", 0.25, "cup", 1.5),
            Context("Baker's Cinnamon Filling", 1.0, "cup", 5.375),
            Context("Baker's Fruit Blend", 1.0, "cup", 4.5),
            Context("Baker's Special Sugar (superfine sugar, castor sugar)", 1.0, "cup", 6.75),
            Context("Baking powder", 1.0, "teaspoon", 0.1410958),
            Context("Baking soda", 0.5, "teaspoon", 0.1058219),
            Context("Baking Sugar Alternative", 1.0, "cup", 6.0),
            Context("Bananas (mashed)", 1.0, "cup", 8.0),
            Context("Barley (cooked)", 1.0, "cup", 7.625),
            Context("Barley (pearled)", 1.0, "cup", 7.5),
            Context("Barley flakes", 0.5, "cup", 1.625),
            Context("Barley flour", 1.0, "cup", 3.0),
            Context("Barley malt syrup", 2.0, "tablespoons", 1.5),
            Context("Basil pesto", 2.0, "tablespoons", 1.0),
            Context("Bell peppers (fresh)", 1.0, "cup", 5.0),
            Context("Berries (frozen)", 1.0, "cup", 5.0),
            Context("Blueberries (dried)", 1.0, "cup", 5.5),
            Context("Blueberries (fresh)", 1.0, "cup", 6.0),
            Context("Blueberry juice", 1.0, "cup", 8.5),
            Context("Boiled cider", 0.25, "cup", 3.0),
            Context("Bran cereal", 1.0, "cup", 2.125),
            Context("Bread crumbs (dried)", 0.25, "cup", 1.0),
            Context("Bread crumbs (fresh)", 0.25, "cup", 0.75),
            Context("Bread crumbs (Japanese Panko)", 1.0, "cup", 1.75),
            Context("Bread Flour", 1.0, "cup", 4.25),
            Context("Brown rice (cooked)", 1.0, "cup", 6.0),
            Context("Brown rice flour", 1.0, "cup", 4.5),
            Context("Brown sugar (dark or light, packed)", 1.0, "cup", 7.5),
            Context("Buckwheat (whole)", 1.0, "cup", 6.0),
            Context("Buckwheat Flour", 1.0, "cup", 4.25),
            Context("Bulgur", 1.0, "cup", 5.375),
            Context("Butter", 8.0, "tablespoons", 4.0),
            Context("Buttermilk", 1.0, "cup", 8.0),
            Context("Buttermilk powder", 2.0, "tablespoons", 0.6666666666666666),
            Context("Cacao nibs", 1.0, "cup", 4.25),
            Context("Cake Enhancer", 2.0, "tablespoons", 0.5),
            Context("Candied peel", 0.5, "cup", 3.0),
            Context("Caramel (14-16 individual pieces, 1in squares)", 0.5, "cup", 5.0),
            Context("Caramel bits (chopped Heath or toffee)", 1.0, "cup", 5.5),
            Context("Caraway seeds", 2.0, "tablespoons", 0.625),
            Context("Carrots (cooked and puréed)", 0.5, "cup", 4.5),
            Context("Carrots (diced)", 1.0, "cup", 5.0),
            Context("Carrots (grated)", 1.0, "cup", 3.5),
            Context("Cashews (chopped)", 1.0, "cup", 4.0),
            Context("Cashews (whole)", 1.0, "cup", 4.0),
            Context("Celery (diced)", 1.0, "cup", 5.0),
            Context("Cheese (Feta)", 0.5, "cup", 2.0),
            Context("Cheese (grated cheddar, jack, mozzarella, or Swiss)", 1.0, "cup", 4.0),
            Context("Cheese (grated Parmesan)", 0.5, "cup", 1.75),
            Context("Cheese (Ricotta)", 1.0, "cup", 8.0),
            Context("Cherries (candied)", 0.25, "cup", 1.75),
            Context("Cherries (dried)", 0.5, "cup", 2.5),
            Context("Cherries (fresh, pitted, chopped)", 0.5, "cup", 2.875),
            Context("Cherries (frozen)", 1.0, "cup", 4.0),
            Context("Cherry Concentrate", 2.0, "tablespoons", 1.5),
            Context("Chickpea flour", 1.0, "cup", 3.0),
            Context("Chives (fresh)", 0.5, "cup", 0.75),
            Context("Chocolate (chopped)", 1.0, "cup", 6.0),
            Context("Chocolate Chips", 1.0, "cup", 6.0),
            Context("Chocolate Chunks", 1.0, "cup", 6.0),
            Context("Cinnamon Sweet Bits", 1.0, "cup", 5.0),
            Context("Cinnamon-Sugar", 0.25, "cup", 1.75),
            Context("Cocoa (unsweetened)", 0.5, "cup", 1.5),
            Context("Coconut (sweetened, shredded)", 1.0, "cup", 3.0),
            Context("Coconut (toasted)", 1.0, "cup", 3.0),
            Context("Coconut (unsweetened, desiccated)", 1.0, "cup", 3.0),
            Context("Coconut (unsweetened, large flakes)", 1.0, "cup", 2.125),
            Context("Coconut (unsweetened, shredded)", 1.0, "cup", 1.875),
            Context("Coconut Flour", 1.0, "cup", 4.5),
            Context("Coconut Milk Powder", 0.5, "cup", 2.0),
            Context("Coconut oil", 0.5, "cup", 4.0),
            Context("Coconut sugar", 0.5, "cup", 2.75),
            Context("Confectioners' sugar (unsifted)", 2.0, "cups", 8.0),
            Context("Cookie crumbs", 1.0, "cup", 3.0),
            Context("Corn (popped)", 4.0, "cups", 0.75),
            Context("Corn syrup", 1.0, "cup", 11.0),
            Context("Cornmeal (whole)", 1.0, "cup", 4.875),
            Context("Cornmeal (yellow, Quaker)", 1.0, "cup", 5.5),
            Context("Cornstarch", 0.25, "cup", 1.0),
            Context("Cracked wheat", 1.0, "cup", 5.25),
            Context("Cranberries (dried)", 0.5, "cup", 2.0),
            Context("Cranberries (fresh or frozen)", 1.0, "cup", 3.5),
            Context("Cream (heavy cream, light cream, or half & half)", 1.0, "cup", 8.0),
            Context("Cream cheese", 1.0, "cup", 8.0),
            Context("Crystallized ginger", 0.5, "cup", 3.25),
            Context("Currants", 1.0, "cup", 5.0),
            Context("Dates (chopped)", 1.0, "cup", 5.25),
            Context("Demerara sugar", 1.0, "cup", 7.75),
            Context("Dried Blueberry Powder", 0.25, "cup", 1.0),
            Context("Dried milk (Baker's Special Dry Milk)", 0.25, "cup", 1.0),
            Context("Dried nonfat milk (powdered)", 0.25, "cup", 1.0),
            Context("Dried potato flakes (instant mashed potatoes)", 0.5, "cup", 1.5),
            Context("Dried whole milk (powdered)", 0.5, "cup", 1.75),
            Context("Durum Flour", 1.0, "cup", 4.375),
            Context("Easy Roll Dough Improver", 2.0, "tablespoons", 0.625),
            Context("Egg (fresh)", 1.0, "large", 1.75),
            Context("Egg white (fresh)", 1.0, "large", 1.25),
            Context("Egg whites (dried)", 2.0, "tablespoons", 0.375),
            Context("Egg yolk (fresh)", 1.0, "large", 0.5),
            Context("Espresso Powder", 1.0, "tablespoon", 0.25),
            Context("Everything Bagel Topping", 0.25, "cup", 1.25),
            Context("Figs (dried, chopped)", 1.0, "cup", 5.25),
            Context("First Clear Flour", 1.0, "cup", 3.75),
            Context("Flax meal", 0.5, "cup", 1.75),
            Context("Flaxseed", 0.25, "cup", 1.25),
            Context("French-Style Flour", 1.0, "cup", 4.25),
            Context("Fruitcake Fruit Blend", 1.0, "cup", 4.25),
            Context("Garlic (cloves, in skin for roasting)", 1.0, "large", 4.0),
            Context("Garlic (minced)", 2.0, "tablespoons", 1.0),
            Context("Garlic (peeled and sliced)", 1.0, "cup", 5.25),
            Context("Ginger (fresh, sliced)", 0.25, "cup", 2.0),
            Context("Gluten-Free All-Purpose Baking Mix", 1.0, "cup", 4.25),
            Context("Gluten-Free All-Purpose Flour", 1.0, "cup", 5.5),
            Context("Gluten-Free Measure for Measure Flour", 1.0, "cup", 4.25),
            Context("Graham cracker crumbs (boxed)", 1.0, "cup", 3.5),
            Context("Graham crackers (crushed)", 1.0, "cup", 5.0),
            Context("Granola", 1.0, "cup", 4.0),
            Context("Grape Nuts", 0.5, "cup", 2.0),
            Context("Harvest Grains Blend", 0.5, "cup", 2.625),
            Context("Hazelnut flour", 1.0, "cup", 3.125),
            Context("Hazelnut Praline Paste", 0.5, "cup", 5.5),
            Context("Hazelnut spread", 0.5, "cup", 5.625),
            Context("Hazelnuts (whole)", 1.0, "cup", 5.0),
            Context("Hi-Maize Natural Fiber", 0.25, "cup", 1.125),
            Context("High-Gluten Flour", 1.0, "cup", 4.25),
            Context("Honey", 1.0, "tablespoon", 0.75),
            Context("Instant ClearJel", 1.0, "tablespoon", 0.375),
            Context("Irish-Style Flour", 1.0, "cup", 3.875),
            Context("Italian-Style Flour", 1.0, "cup", 3.75),
            Context("Jam or preserves", 0.25, "cup", 3.0),
            Context("Jammy Bits", 1.0, "cup", 6.5),
            Context("Keto Wheat Flour", 1.0, "cup", 4.25),
            Context("Key Lime Juice", 1.0, "cup", 8.0),
            Context("Lard", 0.5, "cup", 4.0),
            Context("Leeks (diced)", 1.0, "cup", 3.25),
            Context("Lemon Juice Powder", 2.0, "tablespoons", 0.625),
            Context("Lime Juice Powder", 2.0, "tablespoons", 0.625),
            Context("Macadamia nuts (whole)", 1.0, "cup", 5.25),
            Context("Malt syrup", 2.0, "tablespoons", 1.5),
            Context("Malted Milk Powder", 0.25, "cup", 1.25),
            Context("Malted Wheat Flakes", 0.5, "cup", 2.25),
            Context("Maple sugar", 0.5, "cup", 2.75),
            Context("Maple syrup", 0.5, "cup", 5.5),
            Context("Marshmallow crème", 1.0, "cup", 3.0),
            Context("Marshmallow Fluff®", 1.0, "cup", 4.5),
            Context("Marshmallows (mini)", 1.0, "cup", 1.5),
            Context("Marzipan", 1.0, "cup", 10.125),
            Context("Mascarpone cheese", 1.0, "cup", 8.0),
            Context("Mashed potatoes", 1.0, "cup", 7.5),
            Context("Mayonnaise", 0.5, "cup", 4.0),
            Context("Medium Rye Flour", 1.0, "cup", 3.75),
            Context("Meringue powder", 0.25, "cup", 1.5),
            Context("Milk (evaporated)", 0.5, "cup", 4.0),
            Context("Milk (fresh)", 1.0, "cup", 8.0),
            Context("Millet (whole)", 0.5, "cup", 3.625),
            Context("Mini chocolate chips", 1.0, "cup", 6.25),
            Context("Molasses", 0.25, "cup", 3.0),
            Context("Mushrooms (sliced)", 1.0, "cup", 2.75),
            Context("Non-Diastatic Malt Powder", 2.0, "tablespoons", 0.625),
            Context("Oat bran", 0.5, "cup", 1.875),
            Context("Oat flour", 1.0, "cup", 3.25),
            Context("Oats (old-fashioned or quick-cooking)", 1.0, "cup", 3.125),
            Context("Olive oil", 0.25, "cup", 1.75),
            Context("Olives (sliced)", 1.0, "cup", 5.0),
            Context("Onions (fresh, diced)", 1.0, "cup", 5.0),
            Context("Paleo Baking Flour", 1.0, "cup", 3.625),
            Context("Palm shortening", 0.25, "cup", 1.5),
            Context("Passion fruit purée ", 0.3333333333333333, "cup", 2.125),
            Context("Pasta Flour Blend", 1.0, "cup", 5.125),
            Context("Pastry Flour", 1.0, "cup", 3.75),
            Context("Pastry Flour Blend", 1.0, "cup", 4.0),
            Context("Peaches (peeled and diced)", 1.0, "cup", 6.0),
            Context("Peanut butter", 0.5, "cup", 4.75),
            Context("Peanuts (whole, shelled)", 1.0, "cup", 5.0),
            Context("Pears (peeled and diced)", 1.0, "cup", 5.75),
            Context("Pecan Meal", 1.0, "cup", 2.75),
            Context("Pecans (diced)", 0.5, "cup", 2.0),
            Context("Pie Filling Enhancer", 0.25, "cup", 1.625),
            Context("Pine nuts", 0.5, "cup", 2.5),
            Context("Pineapple (dried)", 0.5, "cup", 2.5),
            Context("Pineapple (fresh or canned, diced)", 1.0, "cup", 6.0),
            Context("Pistachio nuts (shelled)", 0.5, "cup", 2.125),
            Context("Pistachio Paste", 0.25, "cup", 2.75),
            Context("Pizza Dough Flavor", 2.0, "tablespoons", 0.4232875),
            Context("Pizza Flour", 1.0, "cup", 4.0),
            Context("Pizza Flour Blend", 1.0, "cup", 4.375),
            Context("Polenta (coarse ground cornmeal)", 1.0, "cup", 5.75),
            Context("Poppy seeds", 2.0, "tablespoons", 0.625),
            Context("Potato Flour", 0.25, "cup", 1.625),
            Context("Potato starch", 1.0, "cup", 5.375),
            Context("Pumpernickel Flour", 1.0, "cup", 3.75),
            Context("Pumpkin purée ", 1.0, "cup", 8.0),
            Context("Quinoa (cooked)", 1.0, "cup", 6.5),
            Context("Quinoa (whole)", 1.0, "cup", 6.25),
            Context("Quinoa flour", 1.0, "cup", 3.875),
            Context("Raisins (loose)", 1.0, "cup", 5.25),
            Context("Raisins (packed)", 0.5, "cup", 3.0),
            Context("Raspberries (fresh)", 1.0, "cup", 4.25),
            Context("Rhubarb (sliced, 1/2in slices)", 1.0, "cup", 4.25),
            Context("Rice (long grain, dry)", 0.5, "cup", 3.5),
            Context("Rice flour (white)", 1.0, "cup", 5.0),
            Context("Rice Krispies", 1.0, "cup", 1.0),
            Context("Rye Bread Improver", 2.0, "tablespoons", 0.4938355),
            Context("Rye Chops", 1.0, "cup", 4.25),
            Context("Rye flakes", 1.0, "cup", 4.375),
            Context("Rye Flour Blend", 1.0, "cup", 3.75),
            Context("Salt (Kosher, Diamond Crystal)", 1.0, "tablespoon", 0.2821917),
            Context("Salt (Kosher, Morton's)", 1.0, "tablespoon", 0.5643834),
            Context("Salt (table)", 1.0, "tablespoon", 0.6349313),
            Context("Scallions (sliced)", 1.0, "cup", 2.25),
            Context("Self-Rising Flour", 1.0, "cup", 4.0),
            Context("Semolina Flour", 1.0, "cup", 5.75),
            Context("Sesame seeds", 0.5, "cup", 2.5),
            Context("Shallots (peeled and sliced)", 1.0, "cup", 5.5),
            Context("Six-Grain Blend", 1.0, "cup", 4.5),
            Context("Sorghum flour", 1.0, "cup", 4.875),
            Context("Sour cream", 1.0, "cup", 8.0),
            Context("Sourdough starter", 1.0, "cup", 8.25),
            Context("Soy flour", 0.25, "cup", 1.25),
            Context("Sparkling Sugar", 0.25, "cup", 2.0),
            Context("Spelt Flour", 1.0, "cup", 3.5),
            Context("Sprouted Wheat Flour", 1.0, "cup", 4.0),
            Context("Steel cut oats", 0.5, "cup", 2.5),
            Context("Sticky Bun Sugar", 1.0, "cup", 3.5),
            Context("Strawberries (fresh sliced)", 1.0, "cup", 5.875),
            Context("Sugar (granulated white)", 1.0, "cup", 7.0),
            Context("Sugar substitute (Splenda)", 1.0, "cup", 0.875),
            Context("Sundried tomatoes (dry pack)", 1.0, "cup", 6.0),
            Context("Sunflower seeds", 0.25, "cup", 1.25),
            Context("Super 10 Blend", 1.0, "cup", 3.75),
            Context("Sweet Ground Chocolate and Cocoa Blend", 0.25, "cup", 1.0),
            Context("Sweetened condensed milk", 0.25, "cup", 2.75),
            Context("Tahini paste", 0.5, "cup", 4.5),
            Context("Tapioca starch or flour", 1.0, "cup", 4.0),
            Context("Tapioca (quick cooking)", 2.0, "tablespoons", 0.75),
            Context("Teff flour", 1.0, "cup", 4.75),
            Context("The Works Bread Topping", 0.25, "cup", 1.25),
            Context("Toasted Almond Flour", 1.0, "cup", 3.375),
            Context("Toffee chunks", 1.0, "cup", 5.5),
            Context("Tropical Fruit Blend", 1.0, "cup", 4.75),
            Context("Turbinado sugar (raw)", 1.0, "cup", 6.375),
            Context("Unbleached Cake Flour", 1.0, "cup", 4.25),
            Context("Vanilla Extract ", 1.0, "tablespoon", 0.5),
            Context("Vegetable oil", 1.0, "cup", 7.0),
            Context("Vegetable shortening", 0.25, "cup", 1.625),
            Context("Vermont Cheese Powder", 0.5, "cup", 2.0),
            Context("Vital Wheat Gluten", 2.0, "tablespoons", 0.625),
            Context("Walnuts (chopped)", 1.0, "cup", 4.0),
            Context("Walnuts (whole)", 0.5, "cup", 2.25),
            Context("Wheat berries (red)", 1.0, "cup", 6.5),
            Context("Wheat bran", 0.5, "cup", 1.125),
            Context("Wheat germ", 0.25, "cup", 1.0),
            Context("White Chocolate Chips", 1.0, "cup", 6.0),
            Context("White Rye Flour", 1.0, "cup", 3.75),
            Context("White Whole Wheat Flour", 1.0, "cup", 4.0),
            Context("Whole Grain Flour Blend", 1.0, "cup", 4.0),
            Context("Whole Wheat Flour (Premium 100%)", 1.0, "cup", 4.0),
            Context("Whole Wheat Pastry Flour / Graham Flour", 1.0, "cup", 3.375),
            Context("Yeast (instant)", 1.0, "tablespoon", 0.3333333333333333),
            Context("Yogurt", 1.0, "cup", 8.0),
            Context("Zucchini (shredded)", 1.0, "cup", 4.75),
            ]


def main(args):
    return {"body": "hello"}

